[package]
name = "rari"
version = "0.2.1"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = [ "rlib" ]

[[bin]]
name = "rari"
path = "src/bin/rari.rs"

[dependencies]
# === Core Runtime Dependencies ===
deno_core = "0.352.1"
deno_error = "=0.6.1"
deno_features = "0.8.0"
deno_runtime = "0.219.0"
deno_permissions = "0.70.0"
deno_process = "0.26.0"

# === Essential Web APIs ===
deno_console = "0.211.0"
deno_crypto = "0.225.0"
deno_fetch = "0.235.0"
deno_url = "0.211.0"
deno_web = "0.242.0"
deno_webidl = "0.211.0"
deno_broadcast_channel = "0.205.0"
deno_cache = "0.143.0"
deno_webstorage = "0.206.0"

# === Network & HTTP ===
deno_http = "0.209.0"
deno_net = "0.203.0"
deno_tls = "0.198.0"
deno_websocket = "0.216.0"

# === File System & I/O ===
deno_fs = "0.121.0"
deno_io = "0.121.0"

# === Advanced Features ===
deno_telemetry = "0.33.0"
deno_terminal = "=0.2.2"
deno_webgpu = "0.178.0"
deno_kv = "0.119.0"
deno_cron = "0.91.0"

# === Node.js Integration ===
deno_node = "0.149.0"
deno_resolver = "0.42.0"
node_resolver = "0.49.0"

# === FFI & NAPI ===
deno_ffi = "0.198.0"
deno_napi = "0.142.0"

# === Async & Concurrency ===
async-stream = "0.3.6"
async-trait = "0.1.88"
futures = { version = "0.3.31", features = [ "std" ] }
futures-util = "0.3.31"
tokio = { version = "1.47.1", features = [ "full" ] }

# === JavaScript Transformation ===
oxc = { version = "0.69.0", features = [
  "codegen",
  "transformer",
  "semantic"
] }

# === Serialization ===
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.142"
toml = "0.8"

# === HTTP Client & Server ===
http = "1.3"
reqwest = { version = "0.12.22", features = [
  "json",
  "stream",
  "rustls-tls"
], default-features = false }
axum = { version = "0.7", features = [
  "ws",
  "macros"
] }
tower = { version = "0.4", features = [ "full" ] }
tower-http = { version = "0.5", features = [
  "fs",
  "cors",
  "trace"
] }
colored = "2.2"
urlencoding = "2.1"
tokio-tungstenite = { version = "0.21", features = [ "rustls-tls-native-roots" ] }
tungstenite = "0.21"

# === Utilities ===
dashmap = "6.1.0"
parking_lot = "0.12.4"
smallvec = { version = "1.15.1", features = [ "serde" ] }
regex = "^1.11.1"
rustc-hash = "2.1.1"
uuid = { version = "1.18.0", features = [
  "v4",
  "serde"
] }
thiserror = "2.0.14"
chrono = { version = "0.4", features = [ "serde" ] }

# === System Integration ===
hyper-util = { version = "0.1.16", features = [
  "tokio",
  "client",
  "client-legacy",
  "server",
  "server-auto",
] }
libc = "0.2.175"
nix = { version = "=0.27.1", features = [ "term" ] }
sys_traits = "=0.1.17"
sysinfo = "0.36.1"

# === Development Tools ===
rustyline = "=13.0.0"
deno_ast = { version = "0.48.2", features = [ "transpiling" ] }
deno_package_json = { version = "0.13.0", default-features = false }
deno_semver = "0.8.1"

# === Platform-specific Dependencies ===
winapi = { version = "0.3.9", features = [
  "wincon",
  "handleapi",
  "consoleapi",
  "minwindef"
] }

# === CLI & Logging ===
clap = { version = "4.5.44", features = [ "derive" ] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.19", features = [ "env-filter" ] }
dotenv = "0.15.0"

# === TLS & Crypto ===
rustls = { version = "=0.23.28", default-features = false, features = [
  "logging",
  "std",
  "tls12",
  "ring"
] }

[dev-dependencies]
tracing-test = "0.2"
