[package]
name = "rari"
version = "0.2.6"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = [ "rlib" ]

[[bin]]
name = "rari"
path = "src/bin/rari.rs"

[dependencies]
# === Core Runtime Dependencies ===
deno_core = "0.355.0"
deno_error = "=0.7.0"
deno_features = "0.10.0"
deno_runtime = "0.221.0"
deno_permissions = "0.72.0"
deno_process = "0.28.0"

# === Essential Web APIs ===
deno_console = "0.213.0"
deno_crypto = "0.227.0"
deno_fetch = "0.237.0"
deno_url = "0.213.0"
deno_web = "0.244.0"
deno_webidl = "0.213.0"
deno_broadcast_channel = "0.207.0"
deno_cache = "0.145.0"
deno_webstorage = "0.208.0"

# === Network & HTTP ===
deno_http = "0.211.0"
deno_net = "0.205.0"
deno_tls = "0.200.0"
deno_websocket = "0.218.0"

# === File System & I/O ===
deno_fs = "0.123.0"
deno_io = "0.123.0"

# === Advanced Features ===
deno_telemetry = "0.35.0"
deno_terminal = "=0.2.2"
deno_webgpu = "0.180.0"
deno_kv = "0.121.0"
deno_cron = "0.93.0"

# === Node.js Integration ===
deno_node = "0.151.0"
deno_resolver = "0.44.0"
node_resolver = "0.51.0"

# === FFI & NAPI ===
deno_ffi = "0.200.0"
deno_napi = "0.144.0"

# === Async & Concurrency ===
async-stream = "0.3.6"
async-trait = "0.1.89"
futures = { version = "0.3.31", features = [ "std" ] }
futures-util = "0.3.31"
tokio = { version = "1.47.1", features = [ "full" ] }

# === JavaScript Transformation ===
oxc = { version = "0.82.3", features = [
  "codegen",
  "transformer",
  "semantic"
] }

# === Serialization ===
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0.143"
toml = "0.9.5"

# === HTTP Client & Server ===
http = "1.3.1"
reqwest = { version = "0.12.23", features = [
  "json",
  "stream",
  "rustls-tls",
], default-features = false }
axum = { version = "0.8.4", features = [
  "ws",
  "macros"
] }
tower = { version = "0.5.2", default-features = false, features = [ "full" ] }
tower-http = { version = "0.6.6", features = [
  "fs",
  "cors",
  "trace"
] }
colored = "3.0.0"
urlencoding = "2.1.3"
tokio-tungstenite = { version = "0.27", features = [ "rustls-tls-native-roots" ] }
tungstenite = "0.27"

# === Utilities ===
dashmap = "6.1.0"
parking_lot = "0.12.4"
smallvec = { version = "1.15.1", features = [ "serde" ] }
regex = "1.11.1"
rustc-hash = "2.1.1"
uuid = { version = "1.18.0", features = [
  "v4",
  "serde"
] }
thiserror = "2.0.16"
chrono = { version = "0.4", features = [ "serde" ] }

# === System Integration ===
hyper-util = { version = "0.1.16", features = [
  "tokio",
  "client",
  "client-legacy",
  "server",
  "server-auto",
] }
libc = "0.2.175"
nix = { version = "=0.27.1", features = [ "term" ] }
sys_traits = "=0.1.17"
sysinfo = "0.37.0"

# === Development Tools ===
rustyline = "=13.0.0"
deno_ast = { version = "=0.49", features = [ "transpiling" ] }
deno_package_json = { version = "0.15.0", default-features = false }
deno_semver = "=0.9.0"

# === Platform-specific Dependencies ===
winapi = { version = "0.3.9", features = [
  "wincon",
  "handleapi",
  "consoleapi",
  "minwindef",
] }

# === CLI & Logging ===
clap = { version = "4.5.45", features = [ "derive" ] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [ "env-filter" ] }
dotenvy = "0.15.7"

# === TLS & Crypto ===
rustls = { version = "=0.23.28", default-features = false, features = [
  "logging",
  "std",
  "tls12",
  "aws_lc_rs",
] }

[dev-dependencies]
tracing-test = "0.2.5"
