[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --shamefully-hoist && pnpm run build"
nixpacksPlan = { phases = { setup = { nixPkgs = [
  "nodejs-22_x",
  "pnpm"
] } } }

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
