[build]
builder = "NIXPACKS"
buildCommand = "rm -rf node_modules package-lock.json pnpm-lock.yaml && pnpm install && pnpm run build"
nixpacksPlan = { phases = { setup = { nixPkgs = [
  "nodejs_22",
  "pnpm"
] } } }

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
